# Generated by Django 3.0.3 on 2020-06-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120)),
                ('project_description', models.CharField(max_length=400)),
                ('project_link', models.CharField(max_length=500)),
                ('project_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
